language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
#  - zip -r springboot-aws-webservice *
#  - mkdir -p deploy
#  - mv springboot-aws-webservice.zip deploy/springboot-aws-webservice
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # 이동 전 전체압축
  - cd ../ && mkdir -p deploy # 상위 이동 후 deploy dir 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-aws-webservice.zip # 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정
    bucket: springboot-aws-webservice-build # S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # repo settings 내에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-aws-webservice-build # S3버킷
    key: springboot-aws-webservice
    bundle_type: zip
    application: springboot-aws-webservice # 콘솔 등록 어플리케이션
    deployment_group: springboot-aws-webservice # 콘솔 codeDeploy 배포그룹
    region: ap-northeast-2
    wait_until_deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - siznorias@gmail.com